# -*- coding: utf-8 -*-
"""OCR_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117ckGLK-XtLO3s7UwiWman508_hE0wEP
"""

!apt-get install tesseract-ocr -y
!pip install pytesseract opencv-python pillow

import cv2
import pytesseract
from PIL import Image

# Load image
img = cv2.imread('/content/batch1-0001.jpg')

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply threshold
thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)[1]

# Save processed image
cv2.imwrite("processed.png", thresh)

# OCR
text = pytesseract.image_to_string(thresh)

print("Extracted Text:")
print(text)

with open("output.txt", "w") as f:
    f.write(text)

print("Text saved to output.txt")

!unzip dataset.zip

import cv2
import os

input_folder = "/content/dataset"
output_folder = "/content/preprocessed"

os.makedirs(output_folder, exist_ok=True)

for file in os.listdir(input_folder):
    img_path = os.path.join(input_folder, file)
    img = cv2.imread(img_path)

    if img is None:
        continue

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray, (5,5), 0)
    thresh = cv2.threshold(blur, 150, 255, cv2.THRESH_BINARY)[1]

    out_path = os.path.join(output_folder, file)
    cv2.imwrite(out_path, thresh)

print("Preprocessing completed.")

import pytesseract
from PIL import Image
import os

ocr_output = {}

for file in os.listdir("/content/preprocessed"):
    img_path = "/content/preprocessed/" + file
    text = pytesseract.image_to_string(Image.open(img_path))
    ocr_output[file] = text

    print("------", file, "------")
    print(text)

import re

def extract_fields(text):
    invoice_no = re.findall(r'INV[-\s]?\d+', text)
    date = re.findall(r'\d{2}/\d{2}/\d{4}', text)
    amount = re.findall(r'\₹?\$?\d+\.\d{2}', text)

    return {
        "Invoice Number": invoice_no[0] if invoice_no else "Not found",
        "Date": date[0] if date else "Not found",
        "Amount": amount[0] if amount else "Not found"
    }

structured_data = {}

for file, text in ocr_output.items():
    structured_data[file] = extract_fields(text)

structured_data

ground_truth = {
    "batch1-0001.jpg": {"Date": "04/13/2013", "Amount": "3.20"},
    "batch1-0005.jpg": {"Date": "10/29/2016", "Amount": "3.00"},
    "batch1-0006.jpg": {"Date": "Not found", "Amount": "3.00"},
    "batch1-0007.jpg": {"Date": "11/24/2019", "Amount": "5.25"},
    "batch1-0008.jpg": {"Date": "01/05/2017", "Amount": "Not found"}
}

correct = 0
total = 0

for file in ground_truth:
    for field in ground_truth[file]:
        total += 1
        if structured_data[file][field] == ground_truth[file][field]:
            correct += 1

accuracy = correct / total
accuracy

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pytesseract
# import cv2
# import re
# from PIL import Image
# import numpy as np
# 
# st.title("OCR Document Processing System")
# 
# uploaded_file = st.file_uploader("Upload Invoice Image", type=["jpg","png","jpeg"])
# 
# def extract_fields(text):
#     invoice_no = re.findall(r'INV[-\s]?\d+', text)
#     date = re.findall(r'\d{2}/\d{2}/\d{4}', text)
#     amount = re.findall(r'\₹?\$?\d+\.\d{2}', text)
# 
#     return {
#         "Invoice Number": invoice_no[0] if invoice_no else "Not found",
#         "Date": date[0] if date else "Not found",
#         "Amount": amount[0] if amount else "Not found"
#     }
# 
# if uploaded_file:
#     image = Image.open(uploaded_file)
#     img = np.array(image)
# 
#     gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#     thresh = cv2.threshold(gray, 150, 255, cv2.THRESH_BINARY)[1]
# 
#     text = pytesseract.image_to_string(thresh)
# 
#     st.subheader("Extracted Text")
#     st.write(text)
# 
#     fields = extract_fields(text)
# 
#     st.subheader("Structured Output")
#     st.json(fields)

!streamlit run app.py & npx localtunnel --port 8501

structured_data
print(text)

http://34.67.9.246:8501